name: sfmc_plugin
description: Salesforce Marketing Cloud (SFMC) - MobilePush SDK for Flutter. Implement the MobilePush SDK for your iOS and Android applications in Flutter.
version: 3.2.1
homepage: https://github.com/sefidgaran/salesforce-marketing-cloud

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sfmc_plugin
        pluginClass: SfmcPlugin
      ios:
        pluginClass: SfmcPlugin
